version: '3.8'

services:
  mysql-security:
    image: mysql:latest
    container_name: mysql-security-container
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=db_security
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - mysql-security-data:/var/lib/mysql
    networks:
      - net1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-security:3306/db_security
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"
    depends_on:
      - mysql-security
    restart: always
    networks:
      - net1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    
volumes:
  mysql-security-data:

networks:
  net1: